# Generated by Django 3.0.8 on 2020-07-04 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnkleBoot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(verbose_name='Image URL Field')),
                ('product_url', models.URLField(verbose_name='Product URL')),
                ('brand_name', models.CharField(max_length=450, verbose_name='Brand Name')),
                ('product_name', models.CharField(max_length=550, verbose_name='Product Name')),
                ('price', models.IntegerField(verbose_name='Product Price')),
            ],
        ),
        migrations.CreateModel(
            name='Bag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(verbose_name='Image URL Field')),
                ('product_url', models.URLField(verbose_name='Product URL')),
                ('brand_name', models.CharField(max_length=450, verbose_name='Brand Name')),
                ('product_name', models.CharField(max_length=550, verbose_name='Product Name')),
                ('price', models.IntegerField(verbose_name='Product Price')),
            ],
        ),
        migrations.CreateModel(
            name='Coat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(verbose_name='Image URL Field')),
                ('product_url', models.URLField(verbose_name='Product URL')),
                ('brand_name', models.CharField(max_length=450, verbose_name='Brand Name')),
                ('product_name', models.CharField(max_length=550, verbose_name='Product Name')),
                ('price', models.IntegerField(verbose_name='Product Price')),
            ],
        ),
        migrations.CreateModel(
            name='Dress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(verbose_name='Image URL Field')),
                ('product_url', models.URLField(verbose_name='Product URL')),
                ('brand_name', models.CharField(max_length=450, verbose_name='Brand Name')),
                ('product_name', models.CharField(max_length=550, verbose_name='Product Name')),
                ('price', models.IntegerField(verbose_name='Product Price')),
            ],
        ),
        migrations.CreateModel(
            name='Pullover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(verbose_name='Image URL Field')),
                ('product_url', models.URLField(verbose_name='Product URL')),
                ('brand_name', models.CharField(max_length=450, verbose_name='Brand Name')),
                ('product_name', models.CharField(max_length=550, verbose_name='Product Name')),
                ('price', models.IntegerField(verbose_name='Product Price')),
            ],
        ),
        migrations.CreateModel(
            name='Sandal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(verbose_name='Image URL Field')),
                ('product_url', models.URLField(verbose_name='Product URL')),
                ('brand_name', models.CharField(max_length=450, verbose_name='Brand Name')),
                ('product_name', models.CharField(max_length=550, verbose_name='Product Name')),
                ('price', models.IntegerField(verbose_name='Product Price')),
            ],
        ),
        migrations.CreateModel(
            name='Shirt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(verbose_name='Image URL Field')),
                ('product_url', models.URLField(verbose_name='Product URL')),
                ('brand_name', models.CharField(max_length=450, verbose_name='Brand Name')),
                ('product_name', models.CharField(max_length=550, verbose_name='Product Name')),
                ('price', models.IntegerField(verbose_name='Product Price')),
            ],
        ),
        migrations.CreateModel(
            name='Sneaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(verbose_name='Image URL Field')),
                ('product_url', models.URLField(verbose_name='Product URL')),
                ('brand_name', models.CharField(max_length=450, verbose_name='Brand Name')),
                ('product_name', models.CharField(max_length=550, verbose_name='Product Name')),
                ('price', models.IntegerField(verbose_name='Product Price')),
            ],
        ),
        migrations.CreateModel(
            name='TopAndTshirt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(verbose_name='Image URL Field')),
                ('product_url', models.URLField(verbose_name='Product URL')),
                ('brand_name', models.CharField(max_length=450, verbose_name='Brand Name')),
                ('product_name', models.CharField(max_length=550, verbose_name='Product Name')),
                ('price', models.IntegerField(verbose_name='Product Price')),
            ],
        ),
        migrations.CreateModel(
            name='Trouser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(verbose_name='Image URL Field')),
                ('product_url', models.URLField(verbose_name='Product URL')),
                ('brand_name', models.CharField(max_length=450, verbose_name='Brand Name')),
                ('product_name', models.CharField(max_length=550, verbose_name='Product Name')),
                ('price', models.IntegerField(verbose_name='Product Price')),
            ],
        ),
    ]
